config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  # resources :stores, only: [:index, :new, :create, :show, :edit, :destroy, :update]
  resources :stores
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord

  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resources)
    stores_path(resources)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = current_user.stores.order("created_at desc").page(params[:page]).per(9)
  end

  def new
    @store = Store.new
  end

  def create
    Store.create(stores_params)
    redirect_to stores_path
  end

  def show
    @store = Store.find(params[:id])
  end

  def edit
    @store = Store.find(params[:id])
  end

  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    
    redirect_to stores_path
    
  end

  def update
    @stores = Store.find(params[:id])
    @stores.update(stores_params)
    redirect_to stores_path
  end

  def search
    @store = Store.search(params[:keyword])
  end

  private
  def stores_params
    params.require(:store).permit(:name, :address, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/top.html.haml
%body
  #home.big-bg
    %header.page-header.wrapper
      %h1
        = link_to root_path do
          %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
      %nav
        %ul.main-nav
          %li
            - if user_signed_in?
              = link_to new_store_path do
                新規投稿
          %li
            - if user_signed_in?
              = link_to stores_path do
                Menu

    .home-content.wrapper
      %h2.page-title Welcome to your record
      %p あなたによる、あなただけのグルメまとめ。信じるは自分の味覚のみ。
      %p
        - if user_signed_in?
          = link_to "Logout", destroy_user_session_path, method: :delete, class: "user-btn"
        - else
          = link_to "Login", new_user_session_path, class: "user-btn"
          = link_to "新規登録", new_user_registration_path, class: "user-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Takulog
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / コード追加　Bootstrap JavaScript読み込みコード
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"}

    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
  

app/views/stores/edit.html.haml
.contents.row
  %header.page-header.wrapper
    %h1
      = link_to root_path do
        %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
    %nav
      %ul.main-nav
        %li
          = link_to new_store_path do
            新規投稿
        %li
          = link_to stores_path do
            Menu
        %li
          - if user_signed_in?
            = link_to "signout", destroy_user_session_path, method: :delete, class: "signout-btn"

    .container

      = form_for @stores do |form|
        %h3
          投稿する
        %p
          = form.text_field :name, placeholder: "Storename"
        %p
          = form.text_field :address, placeholder: "Address"
        %p
          = form.label "画像をアップロード"
          %br/
          = form.file_field :image

        %p
          = form.text_area :text, placeholder: "text", size:30, rows: "10"
        %p
          = form.submit "SEND"

app/views/stores/index.html.haml
%body
  #menu.big-bg
    %header.page-header.wrapper
      %h1
        = link_to root_path do
          %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
      %nav
        %ul.main-nav
          %li
            = link_to new_store_path do
              新規投稿
          %li
            = link_to stores_path do
              Menu
          %li
            - if user_signed_in?
              = link_to "signout", destroy_user_session_path, method: :delete, class: "signout-btn"


    .menu-content.wrapper
      %h2.page-title Menu
      %p
        グルメサイトのレビューに惑わされない。
        自分で確かめ気に入ったお店を保存して自分だけのグルメサイトを作っていきましょう。
        信じるは自分の味覚のみ。

  / /#menu
  .wrapper.grid
    - @stores.each do |store|
      .item
        - if store.image?
          = image_tag store.image.url
        %p.name
          = link_to store_path(store.id) do
            = store.name

  / /.grid
  = paginate @stores

  %footer
    .wrapper
      %p
        %small © 2020 takulog

app/views/stores/new.html.haml
.contents.row
  %header.page-header.wrapper
    %h1
      = link_to root_path do
        %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
    %nav
      %ul.main-nav
        %li
          = link_to new_store_path do
            新規投稿
        %li
          = link_to stores_path do
            Menu
        %li
          - if user_signed_in?
            = link_to "signout", destroy_user_session_path, method: :delete, class: "signout-btn"

    .container

      = form_for @store do |form|
        %h3
          投稿する
        %p
          = form.text_field :name, placeholder: "Storename"
        %p
          = form.text_field :address, placeholder: "Address"
        %p
          = form.label "画像をアップロード"
          %br/
          = form.file_field :image, accept: "image/*", id: "store_image"
        %img#preview/
        %p
          = form.text_area :text, placeholder: "text", size:30, rows: "10"
        %p
          = form.submit "SEND"

app/views/stores/show.html.haml
%body
  #news.big-bg
    %header.page-header.wrapper
      %h1
        = link_to root_path do
          %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
      %nav
        %ul.main-nav
          %li
            = link_to "新規投稿", new_store_path
          %li
            = link_to "Menu", stores_path 
          %li
            - if user_signed_in? && current_user.id == @store.user_id
              = link_to "編集", edit_store_path(@store.id)
            %li
              = link_to "削除", store_path(@store.id), method: :delete
          %li
            - if user_signed_in?
              = link_to "signout", destroy_user_session_path, method: :delete, class: "signout-btn"
    .wrapper
      %h2.page-title Details
    / /.wrapper
  / /#home
  .news-contents.wrapper
    %article
      %header.post-info
        %h2.post-title 
          = @store.name
        %p.post-cat 
          = @store.address
      = image_tag @store.image.url size: '655x400'
      %p.text
        = simple_format(@store.text)
  %footer
    .wrapper
      %p
        %small © 2020 takulog

app/views/users/index.html.haml
%body
  #home.big-bg
    %header.page-header.wrapper
      %h1
        = link_to root_path do
          %img.logo{:alt => "WCBカフェホーム", :src => "/assets/icon.takulog3.png"}/
      -# %nav
      -#   %ul.main-nav
      -#     %li
      -#       %a{:href => "news.html"} News
      -#     %li
      -#       = link_to stores_index_path do
      -#         Menu
    .home-content.wrapper
      %h2.page-title Welcome to your record
      %p あなたによる、あなただけのグルメまとめ。信じるは自分の味覚のみ。
      %p 
        = link_to "ログイン", new_user_session_path, class: "user-btn"
        = link_to "新規登録", new_user_registration_path, class: "user-btn"